[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI for Technical Documentation: Techniques and Strategies for More Effective and Efficient Technical Writing with Technology"
